services:
  audio-language-detector:
    build:
      context: ./audio-language-detector
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL_NAME=${GROQ_MODEL_NAME}
    volumes:
      - common-data:/app/common

  youtube-converter:
    build:
      context: ./youtube-converter
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - common-data:/app/common

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - common-data:/app/common

  tts-executor:
    build:
      context: ./TTS-executor
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - common-data:/app/common

volumes:
  common-data: