services:
  audio-language-detector:
    build:
      context: ./audio-language-detector
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PATH_TO_AUDIO_FILE=${PATH_TO_AUDIO_FILE}
      - GROQ_MODEL_NAME=${GROQ_MODEL_NAME}

  youtube-converter:
    build:
      context: ./youtube-converter
      dockerfile: Dockerfile
    ports:
      - "3333:3333"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"